### ISSUE TITLE
Proposal: Support Non-Standard SYCL Extensions / ComputeCpp compatibility

### ISSUE THREAD

**Issue by psalz** [illuhad/hipSYCL#23] opened 2019-01-22 18:53 UTC
As I’m transitioning my application from ComputeCpp to hipSYCL, I’m realizing that there are many things I’ve been using that aren’t necessarily “SYCL conformant”, or at least somewhat ambiguous with regards to the spec. Supporting those in hipSYCL might seem like a bad idea, but hear me out:

There are many places were the ComputeCpp implementation allows stuff that currently does not compile with hipSYCL. Some things, like having an alternative `<SYCL/sycl.hpp>` entry-point I’m not so sure about (presumably, if SYCL does move away from OpenCL in the future, this might become relevant). Some other things are really convenient though. For example:
-	`cl::sycl::id` and `cl::sycl::range` can not only be constructed from one another (which is in the spec), but also from instances of other dimensionality. For example, if I construct a `cl::sycl::range<3>(cl::sycl::id<1>(5))` I will end up with `{5, 1, 1}` (this of course also works for two `cl::sycl::id` or `cl::sycl::range`).
-	`cl::sycl::id` and `cl::sycl::range` are implicitly 3-dimensional with default values for `index >= dimensions`. For example, `cl::sycl::range<1>(...)[2]` returns `1`.

Now I’d argue that these examples are actually representative of two types of extensions that ComputeCpp makes:
-	The first is a straight-up API extension. If Khronos intended this to exist, it would be listed in the table of constructors for both types (and hopefully it will be in the next version).
-	Since [according to Codeplay](https://www.codeplay.com/portal/08-23-18-codeplay-announces-world-s-first-fully-conformant-sycl-1-2-1-solution), ComputeCpp is passing the Khronos-provided SYCL conformance test suite, I would say that the second example is essentially unspecified behavior.

ComputeCpp is probably the most prevalent SYCL implementation right now, and I suspect that many people will begin their “SYCL journey” with ComputeCpp. Thus, I think for the sake of compatibility (and convenience) we should strive to support a similar feature-set as ComputeCpp.

*However* that being said, I would not necessarily do it by default. There certainly is merit to the idea of having a fully spec-conformant program, especially when trying to target arbitrary SYCL implementations.

I think a good way of approaching this could thus be through feature flags (macros):
-	For example, add a `COMPUTECPP_COMPAT` macro that enables extensions such as the first example.
-	Alternatively, enable it by default and add a `HIPSYCL_STRICT` (or `SYCL_STRICT`) macro that disables these behaviors.

 With regards to the second example – undefined behavior – it’s of course hard to say what e.g. a `HIPSYCL_STRICT` would entail. In any case, I do think that some way or another these (and other) use-cases should be supported.

To be clear: I’m not suggesting to now meticulously compare all the differences between hipSYCL and ComputeCpp and try to reach parity, but rather to have a plan for where I (and others) can put these kinds of extensions whenever they are encountered.

**Comment by illuhad** [comment] 2019-01-22 21:00
I see your point that hipSYCL users will likely come from ComputeCpp, and agree that some level of compatibility would be beneficial.
While your first proposed change is absolutely unproblematic, the second one may have negative performance implications since an accessor in hipSYCL stores a device pointer and a range. If this range is always three-dimensional, it may be larger than necessary and hence increase register pressure for kernels that already need a lot of registers.
With this in mind, I would prefer that such compatibility features are not enabled by default and must be enabled with a `COMPUTECPP_COMPAT` macro.
Perhaps we could even have two modes: a regular compatibility mode that enables everything that's unproblematic and an extended compatibility mode that additionally enables things that may have negative side effects (and perhaps even causes warnings to be emitted so that users are informed that they should change their code)?

**Comment by psalz** [comment] 2019-01-23 18:57
Okay, great to hear that you're open to this! Although now I'm thinking that the macro should definitely be namespaced to hipSYCL, so maybe `HIPSYCL_COMPUTECPP_COMPAT` or something.

I see your point regarding wasting register space, however I suppose this could be worked around through some zero-overhead templating. In any case, I'm not super fixated on getting this particular behavior into hipSYCL, it was just an example of one of the differences that I noticed, which also isn't strictly an API extension.

**Comment by illuhad** [comment] 2019-01-23 22:06
You're right, a namespaced macro is the way to go :)

So, feel free to add the compatibility features you require. As long as it's just an API extension I don't mind. If it has negative side effects we should let the user know that he's doing things wrong ;)

**Comment by illuhad** [comment] 2019-01-30 09:58
(will close this for now; please reopen if other cases of desired ComputeCpp compatibility pop up that are not a bug in ComputeCpp)

**Closed by illuhad** 2019-01-30 09:58 UTC
