### ISSUE TITLE
Atomic accessor problem

### ISSUE THREAD

**Issue by mrzv** [illuhad/hipSYCL#222] opened 2020-03-18 19:41 UTC
I'm running into a strange problem, I'm having trouble debugging. The code is below. It has two options for doing the same thing: iterating over all  elements of a buffer and atomically reading each one.  The first option just has the code in main; the second version hides it in a member function. The first version runs fine, the second version gives the following error:
```
[hipSYCL Error] check_error: Received unknown HIP error 77, throwing memory_allocation_error.
[hipSYCL Error] check_error: Received unknown HIP error 700, throwing memory_allocation_error.
[hipSYCL Error] task_graph: task_done_callback caught async error,  invoking async handler.
[hipSYCL Error] task_graph: submit() caught async error,  invoking async handler.
[hipSYCL Error] SYCL exception details: 'Unknown error occured', HIP error code = 700
```
This is being run on an NVIDIA GPU, if that matters. (On the CPU, both version work fine.)

The code
```
#include <vector>
#include <CL/sycl.hpp>

template<class T>
struct MyBuffer;
template<class T>
struct MyAccessor;

template<class T>
struct MyVector
{
    MyVector(size_t s):
        vec(s)              {}

    MyBuffer<T>    buffer() { return MyBuffer<T>(*this); }

    std::vector<T> vec;
};

template<class T>
struct MyBuffer
{
    MyBuffer(MyVector<T>& v):
        buffer(v.vec.data(), v.vec.size()), n(v.vec.size())  {}

    MyAccessor<T>  access(cl::sycl::handler& cgh)        { return MyAccessor<T>(*this, cgh); }

    cl::sycl::buffer<T> buffer;
    size_t n;
};

template<class T>
struct MyAccessor
{
    MyAccessor(MyBuffer<T>& b, cl::sycl::handler& cgh):
        access(b.buffer.template get_access<cl::sycl::access::mode::atomic>(cgh)), n(b.n)     {}

    void f(size_t u) const
    {
        cl::sycl::atomic<T> a = access[u];
        T x = a.fetch_add(0);   // poor man's load
    }

    void loop(cl::sycl::handler& cgh) const
    {
        cgh.parallel_for<class loop2>(cl::sycl::range<1>(n), [=] (cl::sycl::id<1> tid)
        {
            size_t u = tid[0];
            f(u);
        });
    }

    cl::sycl::accessor<T,  1, cl::sycl::access::mode::atomic, cl::sycl::access::target::global_buffer> access;
    size_t n;
};


int main()
{
    cl::sycl::queue q;

    size_t n = 100;
    using T = std::uint32_t;

    MyVector<T> v(n);

    {
        auto b = v.buffer();

        q.submit([&](cl::sycl::handler& cgh)
        {
            auto a = b.access(cgh);

            // Option 1: works fine
            cgh.parallel_for<class loop1>(cl::sycl::range<1>(n), [=] (cl::sycl::id<1> tid)
            {
                size_t u = tid[0];
                a.f(u);
            });

            // Option 2: problem
            a.loop(cgh);
        });
    }

    return 0;
}
```

**Comment by illuhad** [comment] 2020-03-18 20:08
CUDA error 77 is invalid memory access, if I remember correctly. I suspect the issue is that the kernel submission in `loop()` captures the this pointer instead of capturing the accessor by value. On GPU, the old this pointer from the host is no longer valid and things go horribly wrong.
Please try capturing the accessor by value in `loop()`.

I'm curious, why do you create a new buffer every time someone calls `buffer` (requiring a new host->device data transfer)? Would it not be a better design to have a `unique_ptr<buffer>` or something like that inside `MyVector` that persists once it has been created the first time?

**Comment by mrzv** [comment] 2020-03-18 20:46
Ah, that makes perfect sense. Capturing access explicitly fixes the problem.

But this raises a question. This example is boiled down from a larger exercise. I'm trying to figure out the right way to work with data structures on the device. I was trying to set up a class that captures some complicated data structure and that I can interact with normally within the kernel. Is there some canonical way to do this?

(As for the buffer, your point is well taken. I'll be careful with buffer transfers, but here it would happen just once.)

**Comment by mrzv** [comment] 2020-03-18 21:09
Apparently, since C++17 it's legal to capture `*this` by value, i.e., literally `[*this]() {...}`. And this seems to work and fix this example. I think this means problem solved. Thanks!

**Comment by illuhad** [comment] 2020-03-18 21:56
Praised be the C++17 support in hipSYCL ;)

Happy to hear you got it working. Your question about more complex data structures is still very interesting when talking about pure SYCL 1.2.1, which does not require C++17, so I would like to address this briefly. Even with C++17, strict SYCL 1.2.1 imposes some restrictions on the captured types: It must be trivially copyable and standard layout type (This restriction probably originates from OpenCL kernel `set_arg()` function). This would probably rule out most complex data structures that have custom copy constructor etc.
In hipSYCL, these things work ecause this stuff *just works* in clang CUDA. So in this area, hipSYCL may be more powerful than other SYCL implementations.

So, the way to implement data structures in pure SYCL 1.2.1 is to do it how it is done in pre-SVM OpenCL, which SYCL is based on: Have a structure of `sycl::buffer` objects which store "simple", i.e. trivially copyable types, e.g.:
```
template<class T>
class grid {
private:
  sycl::buffer<sycl::vec<float,2>> cell_center;
  sycl::buffer<T> values;
  float cell_size;
};
```

And yes, more complex, pointer-based data structures such as lists, trees, graphs are an issue at the moment unfortunately. However, the SYCL world is not standing still, and there is the [Intel USM extension](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/USM/USM.adoc) which allows for automatic memory migration between host and device if the hardware supports it (similarly to CUDA unified memory). This extension will very likely end up being implemented in hipSYCL and other SYCL implementations in the future.

**Comment by mrzv** [comment] 2020-03-18 22:41
> Praised be the C++17 support in hipSYCL ;)

Amen. :-)

As for the data structure question, I have assumed that the underlying data has to live in a buffer of simple types. But that's powerful enough. It's straight-forward to implement one's own memory allocator on top of that, and allocate memory as needed. Graphs certainly fit into this model, as do sparse matrices, both of which are what concern me.

My question was more about how to make this work cleanly with member functions (without reverting to C-ism), and I think capture of `*this` by value is the answer.

Anyway, I plan to experiment extensively with this in the next few months, so hopefully I'll uncover lots of issues.

**Comment by keryell** [comment] 2020-03-19 00:43
> > Praised be the C++17 support in hipSYCL ;)
> 
> Amen. :-)

In modern C++ we believe!

Ready to switch to C++20 for the humanity sake? :-)

**Comment by illuhad** [comment] 2020-03-19 00:54
> Ready to switch to C++20 for the humanity sake? :-)

I think the time for this is after the necessary bits are available in a stable, released clang version. My experience with pre-release clangs is not that great - at the moment we have clang 10 segfaulting on us :(

**Comment by mrzv** [comment] 2020-03-19 01:20
>>> Praised be the C++17 support in hipSYCL ;)
>>
>> Amen. :-)
>
> In modern C++ we believe!
> Ready to switch to C++20 for the humanity sake? :-)

I'm starting to see the wisdom in it. ;-)

> I think the time for this is after the necessary bits are available in a stable, released clang version. My experience with pre-release clangs is not that great - at the moment we have clang 10 segfaulting on us :(

Speaking of clang troubles, are there instructions anywhere on how to compile hipSYCL on macOS? Just the CPU version. So far I haven't succeeded. Can't convince CMake that homebrew-installed LLVM really exists.

**Comment by mrzv** [comment] 2020-03-19 01:38
Let me correct the last statement. I can convince CMake that LLVM exists by setting
```
export CMAKE_PREFIX_PATH=/usr/local/opt/llvm
```
but there is a bunch of linking problems.

**Comment by illuhad** [comment] 2020-03-19 10:28
> Speaking of clang troubles, are there instructions anywhere on how to compile hipSYCL on macOS? Just the CPU version. So far I haven't succeeded. Can't convince CMake that homebrew-installed LLVM really exists.

I have no experience with MacOS, and don't have access to mac machines for testing. So, no, there is no documentation since I cannot really support this use case. Additionally, it's not really an interesting OS to target for us since AMD doesn't support ROCm on Mac and NVIDIA is abandoning CUDA support on Mac (CUDA 10.2 will be the last one to support Mac).

Maybe @jeffhammond has some experience with hipSYCL CPU backend on Mac.

**Comment by illuhad** [comment] 2020-03-26 11:07
Closing because original issue was resolved as I understand it, reopen if this is not the case.

**Closed by illuhad** 2020-03-26 11:07 UTC
