### ISSUE TITLE
Error running simple example (AMD RX580)

### ISSUE THREAD

**Issue by MathiasMagnus** [illuhad/hipSYCL#201] opened 2020-02-05 11:23 UTC
Hi!

I installed Manjaro primarily to be able to run SYCL code on up-to-date drivers. If it weren't for that, I'd boot my Ubuntu 16.04 with extremely outdated AMDGPU-PRO drivers still having cl_khr_spir and use ComputeCpp (_and_ get OpenGL interop as well).

I registered the hipsycl repo as per the docs, installed hipsycl, hipsycl-base and hipsycl-rocm. All seems well, rocminfo says:
```
mnagy@GL702ZC-Manjaro ~]$ /opt/hipSYCL/rocm/bin/rocminfo 
ROCk module is loaded
mnagy is member of video group
=====================    
HSA System Attributes    
=====================    
Runtime Version:         1.1
System Timestamp Freq.:  1000.000000MHz
Sig. Max Wait Duration:  18446744073709551615 (0xFFFFFFFFFFFFFFFF) (timestamp count)
Machine Model:           LARGE                              
System Endianness:       LITTLE                             

==========               
HSA Agents               
==========               
*******                  
Agent 1                  
*******                  
  Name:                    AMD Ryzen 7 1700 Eight-Core Processor
  Marketing Name:          AMD Ryzen 7 1700 Eight-Core Processor
  Vendor Name:             CPU                                
  Feature:                 None specified                     
  Profile:                 FULL_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        0(0x0)                             
  Queue Min Size:          0(0x0)                             
  Queue Max Size:          0(0x0)                             
  Queue Type:              MULTI                              
  Node:                    0                                  
  Device Type:             CPU                                
  Cache Info:              
    L1:                      32768(0x8000) KB                   
  Chip ID:                 0(0x0)                             
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   3000                               
  BDFID:                   0                                  
  Internal Node ID:        0                                  
  Compute Unit:            16                                 
  SIMDs per CU:            0                                  
  Shader Engines:          0                                  
  Shader Arrs. per Eng.:   0                                  
  WatchPts on Addr. Ranges:1                                  
  Features:                None
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: KERNARG, FINE GRAINED
      Size:                    32885008(0x1f5c910) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Acessible by all:        TRUE                               
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    32885008(0x1f5c910) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Acessible by all:        TRUE                               
  ISA Info:                
    N/A                      
*******                  
Agent 2                  
*******                  
  Name:                    gfx803                             
  Marketing Name:          Ellesmere [Radeon RX 470/480/570/570X/580/580X/590]
  Vendor Name:             AMD                                
  Feature:                 KERNEL_DISPATCH                    
  Profile:                 BASE_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        128(0x80)                          
  Queue Min Size:          4096(0x1000)                       
  Queue Max Size:          131072(0x20000)                    
  Queue Type:              MULTI                              
  Node:                    1                                  
  Device Type:             GPU                                
  Cache Info:              
    L1:                      16(0x10) KB                        
  Chip ID:                 26591(0x67df)                      
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   1077                               
  BDFID:                   3072                               
  Internal Node ID:        1                                  
  Compute Unit:            36                                 
  SIMDs per CU:            4                                  
  Shader Engines:          4                                  
  Shader Arrs. per Eng.:   1                                  
  WatchPts on Addr. Ranges:4                                  
  Features:                KERNEL_DISPATCH 
  Fast F16 Operation:      FALSE                              
  Wavefront Size:          64(0x40)                           
  Workgroup Max Size:      1024(0x400)                        
  Workgroup Max Size per Dimension:
    x                        1024(0x400)                        
    y                        1024(0x400)                        
    z                        1024(0x400)                        
  Max Waves Per CU:        40(0x28)                           
  Max Work-item Per CU:    2560(0xa00)                        
  Grid Max Size:           4294967295(0xffffffff)             
  Grid Max Size per Dimension:
    x                        4294967295(0xffffffff)             
    y                        4294967295(0xffffffff)             
    z                        4294967295(0xffffffff)             
  Max fbarriers/Workgrp:   32                                 
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    4194304(0x400000) KB               
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Acessible by all:        FALSE                              
    Pool 2                   
      Segment:                 GROUP                              
      Size:                    64(0x40) KB                        
      Allocatable:             FALSE                              
      Alloc Granule:           0KB                                
      Alloc Alignment:         0KB                                
      Acessible by all:        FALSE                              
  ISA Info:                
    ISA 1                    
      Name:                    amdgcn-amd-amdhsa--gfx803          
      Machine Models:          HSA_MACHINE_MODEL_LARGE            
      Profiles:                HSA_PROFILE_BASE                   
      Default Rounding Mode:   NEAR                               
      Default Rounding Mode:   NEAR                               
      Fast f16:                TRUE                               
      Workgroup Max Size:      1024(0x400)                        
      Workgroup Max Size per Dimension:
        x                        1024(0x400)                        
        y                        1024(0x400)                        
        z                        1024(0x400)                        
      Grid Max Size:           4294967295(0xffffffff)             
      Grid Max Size per Dimension:
        x                        4294967295(0xffffffff)             
        y                        4294967295(0xffffffff)             
        z                        4294967295(0xffffffff)             
      FBarrier Max Size:       32                                 
*** Done ***
```
Hitting a few errors in either `syclcc-clang` or the underlying _actual_ Clang, I figured that for AMD architectures, one has to specify the AMD graphics family. My `syclcc.json` looks like this now:
```
[mnagy@GL702ZC-Manjaro SYCL-SAXPY]$ cat /opt/hipSYCL/etc/hipSYCL/syclcc.json 
{
  "default-clang"     : "/opt/hipSYCL/llvm/bin/clang++",
  "default-platform"  : "rocm",
  "default-cuda-path" : "/opt/hipSYCL/cuda",
  "default-gpu-arch"  : "gfx803",
  "default-cpu-cxx"   : "/opt/hipSYCL/llvm/bin/clang++",
  "default-rocm-path" : "/opt/hipSYCL/rocm",
  "default-use-bootstrap-mode" : "false",
  "default-is-dryrun" : "false",
  "default-clang-include-path" : "/opt/hipSYCL/llvm/lib/clang/10.0.0/include",
  "default-rocm-link-line" : "-rpath $HIPSYCL_ROCM_LIB_PATH -rpath $HIPSYCL_ROCM_PATH/hsa/lib -L$HIPSYCL_ROCM_LIB_PATH -lhip_hcc -lamd_comgr -lamd_hostcall -lhsa-runtime64 -latmi_runtime -rpath $HIPSYCL_ROCM_PATH/hcc/lib -L$HIPSYCL_ROCM_PATH/hcc/lib -lmcwamp -lhc_am",
  "default-cuda-link-line" : "-rpath $HIPSYCL_CUDA_LIB_PATH -L$HIPSYCL_CUDA_LIB_PATH -lcudart"
}
```
That being done and being able to compile a simple Main.cpp, I decided to go the CMake route (for which there seems to be no documentation for) and use syclcc-clang as a drop-in replacement to clang with the default config pointing to `gfx803` which is supposedly the right arch for my RX580. Being a VS Code user, that comes as simply as adding an entry
```
{
  "name": "hipSYCL",
  "compilers": {
    "C": "/opt/hipSYCL/llvm/bin/clang",
    "CXX": "/opt/hipSYCL/bin/syclcc-clang"
  }
}
```
to `cmake-tools-kits.json` by which the build goes:
```
[main] Building folder: SYCL-SAXPY 
[build] Starting build
[proc] Executing command: /usr/bin/cmake --build /home/mnagy/Forrás/Repók/Test-Applications/SYCL-SAXPY/build --config Debug --target all -- -j 18
[build] [1/1   0% :: 0.000] Re-running CMake...
[build] -- Configuring done
[build] -- Generating done
[build] -- Build files have been written to: /home/mnagy/Forrás/Repók/Test-Applications/SYCL-SAXPY/build
[build] [2/3  33% :: 4.210] Building CXX object CMakeFiles/SYCL-SAXPY.dir/Options.cpp.o
...
[build] [2/3  66% :: 4.412] Building CXX object CMakeFiles/SYCL-SAXPY.dir/Main.cpp.o
[build] In file included from ../Main.cpp:1:
[build] In file included from ../Options.hpp:4:
[build] In file included from /opt/hipSYCL/bin/../include/CL/sycl.hpp:36:
[build] In file included from /opt/hipSYCL/bin/../include/CL/sycl/backend/backend.hpp:55:
[build] In file included from /opt/hipSYCL/rocm/include/hip/hip_runtime.h:56:
[build] In file included from /opt/hipSYCL/rocm/include/hip/hcc_detail/hip_runtime.h:105:
[build] /opt/hipSYCL/rocm/include/hip/hcc_detail/texture_functions.h:173:5: warning: array designators are a C99 extension [-Wc99-designator]
[build]     [HIP_AD_FORMAT_NOT_INITIALIZED] = 1  ,
[build]     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[build] 1 warning generated when compiling for gfx803.
[build] In file included from ../Main.cpp:1:
[build] In file included from ../Options.hpp:4:
[build] In file included from /opt/hipSYCL/bin/../include/CL/sycl.hpp:36:
[build] In file included from /opt/hipSYCL/bin/../include/CL/sycl/backend/backend.hpp:55:
[build] In file included from /opt/hipSYCL/rocm/include/hip/hip_runtime.h:56:
[build] In file included from /opt/hipSYCL/rocm/include/hip/hcc_detail/hip_runtime.h:105:
[build] /opt/hipSYCL/rocm/include/hip/hcc_detail/texture_functions.h:173:5: warning: array designators are a C99 extension [-Wc99-designator]
[build]     [HIP_AD_FORMAT_NOT_INITIALIZED] = 1  ,
[build]     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[build] 1 warning generated when compiling for host.
[build] [3/3 100% :: 4.602] Linking CXX executable SYCL-SAXPY
[build] Build finished with exit code 0
```
Aside from the warnings triggering withing hipSYCL headers, it builds fine. However, when I try to run my program:
```
[mnagy@GL702ZC-Manjaro SYCL-SAXPY]$ ./build/SYCL-SAXPY 
SYCL-SAXPY sample

Found platform:
        The hipSYCL project

Selected platform: The hipSYCL project
Selected device: Ellesmere [Radeon RX 470/480/570/570X/580/580X/590]

Memory access fault by GPU node-1 (Agent handle: 0x1cd1ca0) on address 0x7800000000. Reason: Page not present or supervisor privilege.
Félbeszakítva (core készült)
```
The code is nothing special, it can be found in my Test-Applications repo under [SYCL-SAXPY](https://github.com/MathiasMagnus/Test-Applications/tree/master/SYCL-SAXPY). I commented out everything related to measuring time on device, as a few classes seem to be missing. Patched [CMakeLists.txt](https://github.com/illuhad/hipSYCL/files/4159161/CMakeLists.txt) is attached which doesn't look for ComputeCpp. Only dep is TCLAP which is readily available in every linux distro's package manager.

**Comment by illuhad** [comment] 2020-02-05 12:37
Hi Mate!

thanks for reporting.

> Aside from the warnings triggering withing hipSYCL headers, it builds fine. 

Those warnings are from AMD's HIP headers (I suppose AMD still doesn't usually test them with clang). The only thing we can do about those is maybe adding a pragma to suppress them.

I don't have an RX580 (or any gfx8 GPU really), but will check if I can reproduce the issue on my Radeon VII at home (don't have AMD GPUs at work unfortunately, which means that hipSYCL is not as well tested on AMD as it could be).

**Comment by illuhad** [comment] 2020-02-05 23:46
My output is: 

```
SYCL-SAXPY sample

Found platform:
        The hipSYCL project

Selected platform: The hipSYCL project
Selected device: Vega 20 [Radeon VII]

Host (validation) execution took: 4111 us.
Result verification passed!
```

so, things seem to work fine on my Radeon VII. Can this be one of those gfx803 specific ROCm issues? Can you confirm that a pure HIP program with similar saxpy functionality compiles and runs fine when compiling with `clang -x hip` ?

---
A couple of general remarks:
* profiling is indeed mostly unimplemented in hipSYCL -- AMD/NVIDIA vendor profilers can be used instead which lowers the implementation priority of this feature for me, although this of course doesn't cover use cases where one would like to obtain measurements within the program as in your case.
* We also have a proper cmake integration, including `add_sycl_to_target()`, so commenting this out is unnecessary. You can also just `find_package(hipSYCL)`. You're absolutely right that we should document this somewhere.
*  > I figured that for AMD architectures, one has to specify the AMD graphics family. My syclcc.json looks like this now

Yes, it's a clang HIP/CUDA frontend thing, nothing inherently specific to hipSYCL. You don't necessarily have to put it in `syclcc.json`, you can also use the environment variable `HIPSYCL_GPU_ARCH` or command line option `--hipsycl-gpu-arch=`. Comand line options override environment variables which override `syclcc.json`. The default value that goes into `syclcc.json` can also be set when configuring hipSYCL with cmake using `-DDEFAULT_GPU_ARCH=`, but of course for the packages we don't know the hardware that will be targeted, so the packages don't provide a default.

**Comment by bd4** [comment] 2020-04-29 12:23
I am seeing the same error with rocm backend on Radeon RX 560 (gfx803). This is the test program I am using:
https://github.com/bd4/dpcpp-test/blob/master/simplebuffer.cxx
this is the output:
```
[GPU  ] Ellesmere [Radeon RX 470/480] {AMD}
Memory access fault by GPU node-1 (Agent handle: 0xfd9f30) on address 0x4800000000. Reason: Page not present or supervisor privilege.
Aborted
```
I built the latest from github using the packaging scripts for ubuntu (although I am on debian stable).

**Comment by illuhad** [comment] 2020-04-29 13:16
As before, please confirm that a regular HIP program with similar functionality works with your ROCm. If you need help for this, let me know. It is known that AMD's gfx8 support on ROCm can be a bit shaky (independently of hipSYCL). Since you both use gfx8 GPUs, I suspect the issue is related to that.

**Comment by bd4** [comment] 2020-04-29 16:16
Thanks @illuhad , I tested with hip-samples and 2_Cookbook/6_dynamic_shared reproduces the problem using the included rocm (/opt/hipSYCL/rocm). My rocm-3.3.0 install (using AMDs debian repository) is able to build and run the example successfully. When I run ldd on the exe produced by syclcc-clang, it appears to be using all the hipSYCL versions, so it doesn't appear to be caused by a mixing of rocm installs (I have LD_LIBRARY_PATH set appropriately), but that is still possible.

I will look into buidling against my existing rocm install, instead of duplicating one inside hipSYCL.

**Comment by bd4** [comment] 2020-04-29 21:42
I was able to resolve this by building from source, using clang 10 from https://apt.llvm.org/ (with openmp, clang, llvm portions all installed) and using the following cmake line:
```
mkdir build && cd build
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=/usr/bin/clang++-10 -DCMAKE_C_COMPILER=/usr/bin/clang-10 -DWITH_ROCM_BACKEND=1 -DWITH_CUDA_BACKEND=1 -DWITH_CPU_BACKEND=1 -DCMAKE_INSTALL_PREFIX=/opt/hipSYCL ..
```
My machine has both an nvidia and amd GPU. Haven't tested nvidia yet, but AMD is working with a simple buffer = index squared example.

**Comment by illuhad** [comment] 2020-04-29 21:50
@bd4 Thank you, this is very valuable information! Was your successful build also using our ROCm or the AMD debian ROCm repository? It would be relatively easy for us to switch to clang 10 if this is the only issue. On the other hand, if it is an issue in ROCm, debugging an error somewhere in ROCm is not fun... Our ROCm builds are based on [aomp](https://github.com/rocm-developer-tools/aomp), in conjunction vanilla clang 9 from the LLVM `release/9.x` branch. Does the issue also occur with the binary aomp builds?

**Comment by bd4** [comment] 2020-04-29 21:57
@illuhad  Yes I installed ROCm using the ubuntu xebian packages as described here: https://rocm-documentation.readthedocs.io/en/latest/Installation_Guide/Installation-Guide.html#ubuntu (I also set env var ROCM_PATH=/opt/rocm but not sure if that was necessary). I do see the "Memory access fault" error when using the 0.8.0 release .deb files downloadable from github. I think I was using the packaging scripts incorrectly, and never really tested 0.8.1 (they are designed to be run after building and installing - I ran them in a way that would just repackage 0.8.0 and give it a new name :P).

**Comment by illuhad** [comment] 2020-04-29 22:04
@bd4 Okay. To narrow down the issue, could you please try
* using the latest packages from our daily [repositories](https://github.com/illuhad/hipSYCL/blob/master/install/scripts/README.md#installing-from-repositories). They are built daily from master and are far newer than the ones from github. We don't have debian packages per se, but the Ubuntu 18.04 ones might work.
* If this doesn't work, using clang 9 from our packages in conjunction with your own ROCm installation to rule out an issue in our LLVM build. In that case it would be certain that the issue is in ROCm.

**Comment by bd4** [comment] 2020-05-01 15:04
@illuhad Works using latest Ubuntu packages (hipsycl-0.8.1-20200501 / hipsycl-{rocm,base}-0.8.1-20200320) from the daily repo. I verified with ldd that it's using the `/opt/hipSYCL/rocm` version of the rocm libraries, and not `/opt/rocm` versions.

Should I still try build from source using clang-9, or do you think you know what cased the issue with the github packages now? I don't see clang 9 in your ubuntu repository, so not sure what you are referring to for that.

**Comment by sbalint98** [comment] 2020-05-01 16:18
Hi @bd4, Actually the base package should contain LLVM including clang-9. the executable should be in the /opt/hipSYCL/llvm/bin folder. If you are interested in how we have built the clang-9 that we ship with the packages you can have a look at the install/scripts/install/install-llvm.sh. Can you confirm that the clang-9 executable is preesnt?

**Comment by bd4** [comment] 2020-05-01 16:30
The executable looks correct:
```
$ /opt/hipSYCL/llvm/bin/clang++ --version
clang version 9.0.1 (https://github.com/llvm/llvm-project c1a0a213378a458fbea1a5c77b315c7dce08fd05)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/hipSYCL/llvm/bin
```
and syclcc.json references it.

**Comment by illuhad** [comment] 2020-07-01 14:09
Fixed in recent packages, so no issue anymore.

**Closed by illuhad** 2020-07-01 14:09 UTC
