### ISSUE TITLE
Received unknown HIP error 700, throwing memory_allocation_error

### ISSUE THREAD

**Issue by arkantos493** [illuhad/hipSYCL#270] opened 2020-06-25 12:46 UTC
```cpp
#include <iostream>
#include <numeric>

#include <CL/sycl.hpp>

namespace sycl = cl::sycl;

class A {
public:
    A(double x) : x(x) { }    

    double get_scaled(double i) const { return x + i; }

private:
    double x;
};

class B {
public:
    B(const A& a) : a(a) { }

    void calc(sycl::queue& queue) const {
        std::vector<double> vec(5);
        std::iota(vec.begin(), vec.end(), 0);
        
        {
            sycl::buffer<double, 1> buf(vec.data(), vec.size());

            queue.submit([&](sycl::handler& cgh) {
                auto acc = buf.get_access<sycl::access::mode::read_write>(cgh);

                cgh.parallel_for<class test>(sycl::range<>(vec.size()), [=](sycl::item<> item) {
                    const std::size_t idx = item.get_linear_id();
                    acc[idx] = a.get_scaled(acc[idx]);
                });
            });
            queue.wait_and_throw();
        }
        
        for (const double d : vec) {
            std::cout << d << ' ';
        }
        std::cout << std::endl;
    }

private:
    const A& a;
};

int main() {
    sycl::queue queue(sycl::default_selector{});
    
    A a(42);
    B b(a);
    b.calc(queue);

    return 0;
}
```
Results in a runtime exception:
```bash
[hipSYCL Error] check_error: Received unknown HIP error [hipSYCL Error] check_error: Received unknown HIP error 700, throwing memory_allocation_error.700, throwing memory_allocation_error.

[hipSYCL Error] task_graph: submit() caught async error,  invoking async handler.
[hipSYCL Error] task_graph: task_done_callback caught async error,  invoking async handler.
[hipSYCL Error] SYCL exception details: 'Unknown error occured', HIP error code = 700
```
Is that the intended behavior? 
And if so is there a "simple" workaround that can be applied without changing the whole program structure?

**Comment by illuhad** [comment] 2020-06-25 13:27
You are capturing a reference, so `a` in your kernel will be invalid because the reference points to host memory, which of course explodes as soon as `a` is accessed. So, yes, this is the intended behavior in a heterogeneous context.

Solution would be either to declare `a` as non-reference, or create an explicit copy before invoking the kernel such it is really copied to device.

**Comment by illuhad** [comment] 2020-07-01 14:04
Closing because probably not caused by hipSYCL.

**Closed by illuhad** 2020-07-01 14:04 UTC
