### ISSUE TITLE
Race condition/dead lock with buffer on const data

### ISSUE THREAD

**Issue by aTom3333** [illuhad/hipSYCL#301] opened 2020-09-13 23:08 UTC
With the following code:
```cpp
#include <cstdio>
#include <vector>
#include <CL/sycl.hpp>

using namespace cl::sycl;

int main(int argc, char *argv[]) {
    const std::vector<float> data = {
            0, 1, 2, 3, 4, 5, 6, 7
    };

    queue q{};
    buffer<float, 1> scene(data.data(), data.size());
    q.submit([&](handler &hdl) {
        auto scn = scene.get_access<access::mode::read>(hdl);
        hdl.parallel_for<class smallpt_kernel>(range<2>(100, 100), [=](id<2> id) {
            int y = id[0], x = id[1];
            printf("%d %d\n", y, x);
        });
    });
} 
```
(executed on the host), I have a race condition where sometimes the kernel is never called. It seems to be 50/50 whether the kernel is called or not, if it is called, it works until the end with no issue, when it is not i have a dead lock.
Thread 1 stackstrace:
```
__lll_lock_wait 0x00007f228b462e2b
__GI___pthread_mutex_lock 0x00007f228b45b843
hipsycl::sycl::detail::task_graph::finish() 0x00007f228b6e782b
hipsycl::sycl::detail::task_graph::~task_graph() 0x00007f228b6e7f96
std::unique_ptr<hipsycl::sycl::detail::runtime, std::default_delete<hipsycl::sycl::detail::runtime> >::~unique_ptr() 0x00007f228b6dbb51
__cxa_finalize 0x00007f228b2c9b96
__do_global_dtors_aux 0x00007f228b6dba63
<unknown> 0x00007ffdef9e6dc0
_dl_fini 0x00007f228b706343
```
Thread 2 stackstrace:
```
hipsycl::sycl::detail::task_graph_node::wait() 0x00007f228b6e6763
hipsycl::sycl::detail::buffer_access_log::wait_dependencies() 0x00007f228b6e2e08
hipsycl::sycl::detail::buffer_impl::~buffer_impl() 0x00007f228b6e2eb5
std::_Sp_counted_ptr<hipsycl::sycl::detail::buffer_impl*, (__gnu_cxx::_Lock_policy)2>::_M_dispose shared_ptr_base.h:380
std::_Function_handler<hipsycl::sycl::detail::task_state (), hipsycl::sycl::detail::buffer_impl::access_host(std::shared_ptr<hipsycl::sycl::detail::buffer_impl>, hipsycl::sycl::access::mode, std::shared_ptr<hipsycl::sycl::detail::stream_manager>, std::function<void (std::vector<std::__exception_ptr::exception_ptr, std::allocator<std::__exception_ptr::exception_ptr> >)>)::{lambda()#1}>::_M_manager(std::_Any_data&, std::_Function_handler<hipsycl::sycl::detail::task_state (), hipsycl::sycl::detail::buffer_impl::access_host(std::shared_ptr<hipsycl::sycl::detail::buffer_impl>, hipsycl::sycl::access::mode, std::shared_ptr<hipsycl::sycl::detail::stream_manager>, std::function<void (std::vector<std::__exception_ptr::exception_ptr, std::allocator<std::__exception_ptr::exception_ptr> >)>)::{lambda()#1}> const&, std::_Manager_operation) 0x00007f228b6e25e0
hipsycl::sycl::detail::task_graph_node::submit() 0x00007f228b6e7489
hipsycl::sycl::detail::task_graph::submit_eligible_tasks() 0x00007f228b6e7775
hipsycl::sycl::detail::task_graph::process_graph() 0x00007f228b6e840b
std::_Function_handler<void (), hipsycl::sycl::detail::task_graph::invoke_async_submission(std::function<void (std::vector<std::__exception_ptr::exception_ptr, std::allocator<std::__exception_ptr::exception_ptr> >)>)::{lambda()#1}>::_M_invoke(std::_Any_data const&) 0x00007f228b6e8455
hipsycl::sycl::detail::worker_thread::work() 0x00007f228b6ea2a6
<unknown> 0x00007f228b59ac60
start_thread 0x00007f228b458ea7
clone 0x00007f228b388eaf
```

If I remove the accessor or if I make the data non-const, no more dead lock.
This might be related to #177

**Comment by illuhad** [comment] 2020-09-13 23:26
Not related to #177.

Probably fixed by using explicit synchronization at the end with `queue::wait()`.

I believe the following happens:
* Input pointer is const, therefore, input memory cannot be modified
* Therefore, input data is copied into the buffer instead of operating directly on it
* Because it's const, no write-back can occur into the original pointer. Since no other write-back operation was provided, no buffer write-back occurs
* Kernel therefore has no observable side-effects and explicit synchronization must be used.

This might be an edge case of the specification though.. But, while it can be argued that this is not well-defined, I'm not sure why hipSYCL won't wait for the kernel anyway. I suspect that the kernel is still in submission phase, and since no write-back follows, nothing waits for the submission to complete.

I would encourage to try with the new runtime (PR #289) which includes a complete rewrite of (among other things) this section of the code and is going to be merged probably tomorrow.

**Comment by aTom3333** [comment] 2020-09-13 23:40
> Kernel therefore has no observable side-effects and explicit synchronization must be used.
I encountered the issue while working that was also using a second buffer to produce data from the input one

> Probably fixed by using explicit synchronization at the end with `queue::wait()`.
You're right, it fixes the issue, thanks.

I'll try with the new runtime and come back to update you

**Comment by keryell** [comment] 2020-09-15 11:16
I do not think this is a real issue in the specification as it was designed on purpose for not having the `sycl::queue` blocking.
Why wasting time to wait for something useless? :-)
In the same way in ISO C++ if a useless `std::thread` is launched but not attended with a `join()` there is a `std::terminate()` down the road.

**Comment by aTom3333** [comment] 2020-09-15 21:49
The issue does not arise with the new runtime.

Also I tried again with the old runtime, I can confirm that with the original that uncovered the issue, the kernel was also using another buffer in write mode (and data is actually written). I made another minimal sample with the issue with an output buffer this time:
```cpp
#include <CL/sycl.hpp>
#include <iostream>
#include <vector>

using namespace cl::sycl;

int main() {
    int n = 5;
    std::vector<float> output(n);
    const std::vector<float> input{1, 2, 3, 4, 5};

    queue q{};
    {
        buffer<float, 1> outBuf(output.data(), output.size());
        buffer<float, 1> inBuf(input.data(), input.size());
        q.submit([&](handler& hdl){
            auto scn = inBuf.get_access<access::mode::read>(hdl);
            auto outAcc = outBuf.get_access<access::mode::write>(hdl);
            hdl.parallel_for<class smallpt_kernel>(range<1>(n), [=](id<1> id){
                printf("%d\n", id[0]);
                outAcc[id] = 0.1;
            });
        });
    }
    
    for(float f : output)
        std::cout << f << " ";
} 
```
With this code, the same issue arises (kernel never called, main thread stuck waiting in a destructor, other threads waiting in the `task_graph_node`)

Interestingly, this program works as expected:
```cpp
#include <CL/sycl.hpp>
#include <iostream>
#include <vector>

using namespace cl::sycl;

int main() {
    int n = 5;
    std::vector<float> output(n);
    const std::vector<float> input{1, 2, 3, 4, 5};

    queue q{};
    {
        buffer<float, 1> inBuf(input.data(), input.size());
        buffer<float, 1> outBuf(output.data(), output.size());
        q.submit([&](handler& hdl){
            auto scn = inBuf.get_access<access::mode::read>(hdl);
            auto outAcc = outBuf.get_access<access::mode::write>(hdl);
            hdl.parallel_for<class smallpt_kernel>(range<1>(n), [=](id<1> id){
                printf("%d\n", id[0]);
                outAcc[id] = 0.1;
            });
        });
    }
    
    for(float f : output)
        std::cout << f << " ";
} 
```
The only difference is that the buffer aren't declared in the same order.
My guess is that with the second program, the output buffer destructor is called first and so we wait for the kernel to be over while the input buffer is still valid, whereas in the first program, the input buffer is destroyed without waiting and is invalid by the time the kernel is called.

**Comment by illuhad** [comment] 2020-09-15 22:23
I don't see how the constructor order could make a difference, so I agree that any effect must come from the destructors being called in a different order in your two examples.

hm..Internally, `buffer` just stores a `shared_ptr` to a `buffer_impl` object which actually contains the data and does the heavy lifting. As long as a copy of this `shared_ptr` exists, the buffer is safe. Kernels capture accessors, which contain a `shared_ptr` to the `buffer_impl`. So it cannot be destroyed while a kernel is still in flight. BUT there is an optimization for non-placeholder and non-host accessors where the `buffer_impl` pointer is only stored inside the command group handler and the accessor only stores an id to the buffer. This can make accessor objects more light-weight. I'm not sure, but it might be that this allows a buffer to be destroyed too early, as you say.
In practice it is however actually more complicated as the `task_graph_node` of the kernel also stores `shared_ptr` objects to its dependencies, which would in general also include buffer operations. I think this would also suffice to prevent the buffer from being destroyed too early, as those operations also are tied to the `buffer_impl`.

The new runtime generalizes the accessor behavior - they always contain a `shared_ptr` to the buffer now, so if this is the reason, this would explain why we don't see it with the new runtime..

In any case, as the new runtime is merged I would prefer to not spend a very large amount on issues that affect code that has been rewritten entirely with the new runtime. Is it critical for you that this is fixed in the old code base?

**Comment by aTom3333** [comment] 2020-09-15 22:50
It is not critical, in fact, as I just started working with SYCL and this is a hobby project (so I don't need stability or whatnot), I already switched to the new runtime (the new runtime also fixes another problem I had that i couldn't reproduce with a minimal example where the CUDA version was super slow. I wasn't even sure if this was a problem with hipSYCL or my code).
Anyway, regarding this issue, as far as I'm concerned, you can close it saying "won't fix"

**Comment by illuhad** [comment] 2020-09-15 23:10
Alright, thanks for the feedback :)

As far as performance goes, the new runtime has a very different task submission model. If you have submitted a lot of very small kernels in your problematic code you might see some significant speedup with the new runtime. But if you have larger kernels and are not bound by runtime performance, I wouldn't expect large performance deltas between the new and old architecture.

**Closed by illuhad** 2020-09-15 23:10 UTC
